### ISSUE TITLE
pascal_voc

### ISSUE THREAD

**Issue by Atubee** [leeyoshinari/YOLO_v2#10]
@leeyoshinari 
Hello,
I don understand line71-74 in pascal_voc.py.
Why the boxes[0] and boxes[1] is added "-np.floor(cx)" and "-np.floor(cy)"?

In yolo_v2.py, The boxes[0] and boxes[1] is not added offset, but  box_coor_trans is added offsets.
Is this not problem? I think this causes problems in iou calculations.

Please, teach me!

**Comment by leeyoshinari** [comment]
You are right, I have tried. Thank you for helping me improve.
