### ISSUE TITLE
关于loss函数一些问题。

### ISSUE THREAD

**Issue by acm5656** [leeyoshinari/YOLO_v2#18]
在yolo_v2.py文件138行，您计算iou使用的box是从126行boxes1变形过来的，但是126行boxes1的w,h是开过平方的，这样不会影响iou的计算吗？另外在yolo2的原文中，w,h没有进行开平方吧，只是在计算loss时，开平方吧。谢谢。
而且我在按照您的说明，进行训练时，发现loss值会出现nan的情况，请问下是什么原因。谢谢。

**Comment by leeyoshinari** [comment]
仔细看一下程序，是平方后计算IOU的，开方是用来计算loss的。
yolo v2的论文中并没有明确指出loss的计算方法，沿用的是yolo v1的计算方法。也可以选择不开方，直接计算loss，但这会影响网络的性能。
loss出现nan，先看看学习速率、初始化参数设置有没有问题，还有训练集和测试集的数据分布要保持一致。

**Comment by acm5656** [comment]
好的，谢谢作者，请问下您有推荐的初始化参数设置和学习速率吗？我在论文中没有找到对应的初始参数的设置，只找到了学习速率的说明。谢谢~。
