### ISSUE TITLE
how to use pretrained weights

### ISSUE THREAD

**Issue by wingerboy** [leeyoshinari/YOLO_v2#21]
There is just one class in my dataset,so,  i couldnt use voc or coco pretrained weights.  Can you tell me how to use pretrained weight file. btw, your link has expired.

**Comment by Stinky-Tofu** [comment]
> There is just one class in my dataset,so, i couldnt use voc or coco pretrained weights. Can you tell me how to use pretrained weight file. btw, your link has expired.

You can only use the weights in front of the last layer.
