### ISSUE TITLE
About train_val

### ISSUE THREAD

**Issue by alimagic** [leeyoshinari/YOLO_v2#23]
Dear author, I would like to ask you a question. I can't download the "yolo_v2.ckpt" mentioned in the code. Can I use "YOLO_tiny.ckpt" or "YOLO_small.ckpt" instead of "yolo_v2.ckpt" for training? Can you give me some advice or help? Thank you.

**Comment by leeyoshinari** [comment]
I'm sorry to reply to you so later. It must use yolo_v2.ckpt.

**Comment by alimagic** [comment]
thank you,i made it,and now i try to understand it😊😊😊
