### ISSUE TITLE
关于ckpt文件

### ISSUE THREAD

**Issue by SpursLipu** [leeyoshinari/YOLO_v2#28]
感谢你的分享
你提供了两套训练好的weights文件，请问为什么我使用你训练的那套weights可以运行，但是效果很差，根本达不到你demo的那个效果。使用另一套weights就无法运行了，会报错。请问这是怎么回事？

**Comment by leeyoshinari** [comment]
效果很差，此时的loss是多少？？？至于不能运行，看一下错误日志，有可能是tensorflow版本升级导致的。
