### ISSUE TITLE
Could you upload the weight file again? The link is invalid. Thanks！

### ISSUE THREAD

**Issue by violet17** [leeyoshinari/YOLO_v2#3]
Could you upload the weight file again? The link is invalid. Thanks！
Was the weight file converted from darknet website?

**Comment by leeyoshinari** [comment]
The links have fixed. Thanks for your remind.

**Comment by violet17** [comment]
哈哈，我在百度云上Q你了~~~ 国内上不去google网盘，好尴尬啊。。你的百度云里还有没有yolov2的权重啊？

**Comment by leeyoshinari** [comment]
OK

**Comment by violet17** [comment]
O(∩_∩)O谢谢

**Comment by Stinky-Tofu** [comment]
可以把coco的权重给我一份吗？我翻墙也下不了

**Comment by violet17** [comment]
> 可以把coco的权重给我一份吗？我翻墙也下不了

链接: https://pan.baidu.com/s/1-7nNz0hHELMMymfW-RAnQg 提取码: jggc
