### ISSUE TITLE
Assign requires shapes of both tensors to match. lhs shape= [1,1,1024,125] rhs shape= [1,1,1024,425]

### ISSUE THREAD

**Issue by nemesta29** [leeyoshinari/YOLO_v2#36]
Hi,
I tried running the model only from the files provided
-> Downloaded COCO model provided
-> Ran the code without modifications and it gave the above error

I haven't downloaded any data sets because did not seem necessary for testing the model
Kindly guide as to what I can change here, let me know if anything else is required

**Comment by leeyoshinari** [comment]
https://github.com/leeyoshinari/YOLO_v1/issues/3
