### ISSUE TITLE
too many anchor boxes

### ISSUE THREAD

**Issue by ruikun** [leeyoshinari/YOLO_v2#7]
大神你好，
我加载了你提供的VOC数据集的weight继续训练我自己的数据集(只有一个类:house)。
进行到3000+ steps的时候loss突然变成nan，此前在1.0上下波动。
我加载了最新的ckpt，test结果图片上遍布密集的anchor box，如图:
![image](https://user-images.githubusercontent.com/12035229/41097428-25796e3c-6a58-11e8-8980-7d736ca6b593.png)
想请教大佬一下大概是哪里有问题，请问您提供的weight也是通过这个项目训练出来的吗?

**Comment by Nine9Nine** [comment]
可能是训练好的都是20类的吧

**Comment by leeyoshinari** [comment]
别恢复所有层的权重，调整一下学习速率，重新训练试一下

**Comment by ruikun** [comment]
我只有最后一层的weights 变量没有加载，毕竟我自己的数据集只有一个类嘛。
速率的话，已经是0.00001了

**Comment by leeyoshinari** [comment]
最后几层的权重都不要恢复，你再试一下。

**Comment by ruikun** [comment]
请问你是从scratch开始用voc训练的吗?一开始梯度爆炸的问题是怎么解决的?
